src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $location_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $category_id;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $product_id;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private ?string $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $img_link;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $is_img_local;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    public function getLocationId(): ?int
    {
        return $this->location_id;
    }

    public function setLocationId(int $location_id): self
    {
        $this->location_id = $location_id;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(?int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /** @noinspection PhpUnused */
    public function getImgLink(): ?string
    {
        return $this->img_link;
    }

    public function setImgLink(?string $img_link): self
    {
        $this->img_link = $img_link;

        return $this;
    }

    public function getIsImgLocal(): ?bool
    {
        return $this->is_img_local;
    }

    public function setIsImgLocal(bool $is_img_local): self
    {
        $this->is_img_local = $is_img_local;

        return $this;
    }

    public function getCreatedAt(): ?int
    {
        return $this->created_at;
    }

    public function setCreatedAt(int $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?int
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(int $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    // END OF GETTERS AND SETTERS

    /**
     * @return string
     */
    public function getImgPathLink(): string
    {
        if ((int) $this->getIsImgLocal() === 0) {
            return $this->getImgLink();
        }

        return '/img/products/'. pathinfo($this->getImgLink())['basename'];
    }
}

src/Controller/SiteController.php
<?php
namespace App\Controller;

use App\Entity\Feedback;
use App\Form\FeedbackType;
use App\ValueObject\Cities;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SiteController extends AbstractController
{
    /**
     * @Route ("/cities-partial", name="app_cities_partial", methods={"GET"}, priority="1")
     * @param Request $request
     * @return JsonResponse
     */
    public function citiesPartial(Request $request): JsonResponse
    {
        $query = $request->get('query');
        $html = $this->renderView('/site/_partials/cities.html.twig', [
            'cities' => $this->getCities($query),
        ]);

        return $this->json(['html' => $html]);
    }

    /**
     * @param string|null $query
     * @return array
     */
    private function getCities(?string $query): array
    {
        $list = Cities::list();
        if ($query) {
            $res = [];
            foreach ($list as $id => $cityItem) {
                if (strpos(mb_strtolower($cityItem['ru'], 'utf-8'), $query) !== false) {
                    $res[$id] = $cityItem;
                }
            }

            return $res;
        }

        return $list;
    }

    /**
     * @Route ("/select-city/{id}", name="app_select_city", methods={"GET"}, priority="1")
     * @param Request $request
     * @return RedirectResponse
     * @noinspection PhpUnused
     */
    public function selectCity(Request $request): RedirectResponse
    {
        $cityId = $request->get('id');
        setcookie('discountLocationId', $cityId, time() + 604800 * 52, '/');

        return $this->redirectToRoute('app_index');
    }

    /**
     * @Route ("/cities", name="app_cities", methods={"GET"}, priority="1")
     * @return Response
     */
    public function cities(): Response
    {
        $cities = Cities::list();

        return $this->render('/site/cities.html.twig', [
            'cities' => $cities,
        ]);
    }

    /**
     * @Route ("/feedback", name="app_feedback", methods={"GET", "POST"}, priority="1")
     * @param Request $request
     * @return Response
     */
    public function feedback(Request $request): Response
    {
        $feedback = new Feedback();
        $form = $this->createForm(FeedbackType::class, $feedback);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Feedback $feedback */
            $feedback = $form->getData();
            $feedback->setCreatedAt(time());
            $feedback->setUpdatedAt(time());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($feedback);
            $entityManager->flush();
            $entityManager->clear();

            return $this->redirectToRoute('app_index');
        }

        return $this->render('/site/feedback.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/site/cities.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        {% if cities %}
            {% set total = 0 %}
            <div class="col">
                <ul class="list-group">
                {% for id, city in cities %}
                    <li class="list-group-item flex-fill select-city-item">
                        <a href="{{ path('app_select_city', {'id': id} ) }}">{{ city.ru }}</a>
                    </li>

                    {% set total = total + 1 %}
                    {% if total % 15 == 0 %}
                            </ul>
                        </div>
                        <div class="col">
                            <ul class="list-group">
                    {% endif %}
                {% endfor %}
                </ul>
            </div>
        {% else %}
            <div class="col text-center">
                К сожалению, по вашему запросу ничего не найдено
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/site/feedback.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-4">
            <div class="feedback-form mt-4">
                {{ form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for product in favoritedProducts %}
        {% set productDiscountYears = discountYears[product.productId] %}
        <div class="product-block mt-5">
            <div class="row">
                <div class="col-lg-3">
                    <div class="product-card">
                        <div class="row">
                            <div class="col">
                                <img src="{{ product.imgLink }}" class="img-fluid" alt="{{ product.name }}">
                            </div>
                            <div class="col">
                                <div class="product-item-wrapper">
                                    {% if product.productId in activeProductDiscounts|keys %}
                                        {% set discount = activeProductDiscounts[product.productId] %}
                                        {% include '/site/partials/productCard.html.twig' with {
                                            'priceDiscount': discount.priceDiscount,
                                            'priceNormal': discount.priceNormal,
                                            'dateBegin': discount.dateBegin,
                                            'dateEnd': discount.dateEnd
                                        } %}
                                    {% else %}
                                        <div class="pt-3 text-center">
                                            К сожалению, на данный момент по этому продукту нет выгодных предложений
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <small>
                                {% if productDiscountYears|length > 1 %}
                                    <a href="{{ path('product', {'id': product.productId}) }}" target="_blank">{{ product.name }}</a>
                                {% else %}
                                    {{ product.name }}
                                {% endif %}
                                </small>
                            </div>
                        </div>
                        <a href="{{ path('remove_from_favorites', {'productId': product.productId}) }}"
                           class="remove-from-favorites text-danger"
                           title="Удалить из избранного"
                           data-id="{{ product.productId }}"
                        >
                            <i class="fa fa-close"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="discount-history-wrapper">
                        {% set productDiscountDates = discountDates[product.productId]|default([]) %}
                        {% include '/site/partials/history.html.twig' with {
                            'year': year,
                            'yearDates': yearDates,
                            'product': product,
                            'productDiscountDates': productDiscountDates,
                            'productDiscountYears': productDiscountYears,
                        } %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}