src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $location_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $category_id;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $product_id;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private ?string $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $img_link;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $is_img_local;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    public function getLocationId(): ?int
    {
        return $this->location_id;
    }

    public function setLocationId(int $location_id): self
    {
        $this->location_id = $location_id;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(?int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /** @noinspection PhpUnused */
    public function getImgLink(): ?string
    {
        return $this->img_link;
    }

    public function setImgLink(?string $img_link): self
    {
        $this->img_link = $img_link;

        return $this;
    }

    public function getIsImgLocal(): ?bool
    {
        return $this->is_img_local;
    }

    public function setIsImgLocal(bool $is_img_local): self
    {
        $this->is_img_local = $is_img_local;

        return $this;
    }

    public function getCreatedAt(): ?int
    {
        return $this->created_at;
    }

    public function setCreatedAt(int $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?int
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(int $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    // END OF GETTERS AND SETTERS

    /**
     * @return string
     */
    public function getImgPathLink(): string
    {
        if ((int) $this->getIsImgLocal() === 0) {
            return $this->getImgLink();
        }

        return '/img/products/'. pathinfo($this->getImgLink())['basename'];
    }
}

src/Controller/ProductController.php
<?php
namespace App\Controller;

use App\Dto\Location;
use App\Repository\DiscountHistoryRepository;
use App\Repository\DiscountRepository;
use App\Repository\ProductRepository;
use App\Service\ProductItem;
use App\Service\ProductList;
use App\ValueObject\Cities;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ProductController
 * @package App\Controller
 */
class ProductController extends AbstractController
{
    /**
     * @throws Exception
     */
    public function __construct(
        private Location $location,
        private ProductRepository $productRepository,
        private DiscountHistoryRepository $discountHistoryRepository,
        private DiscountRepository $discountRepository
    )
    {
        $this->location = $this->getLocation();
    }

    /**
     * @Route ("/", name="app_index")
     * @return RedirectResponse
     */
    public function index(): RedirectResponse
    {
        return $this->redirectToRoute('app_list', [
            'cityEn' => $this->location->cityNameEn
        ]);
    }

    /**
     * @Route (
     *     "/{cityEn}/{page}",
     *     defaults={"page"=1},
     *     requirements={"cityEn"="\w+", "page"="\d+"},
     *     name="app_list"
     * )
     * @param Request $request
     * @return Response
     * @throws NonUniqueResultException
     * @throws NoResultException
     * @throws Exception
     */
    public function list(Request $request): Response
    {
        $cityEn = $request->get('cityEn');
        $page = (int) $request->get('page', 1);
        $searchQuery = $request->get('q');

        $productList = new ProductList($this->location->cityId, $page, $searchQuery);
        $productList->init($this->productRepository, $this->discountHistoryRepository);
        $productListViewParams = $productList->getProductListViewParams($this->discountRepository);
        $productPaginationViewParams = $productList->getProductPaginationViewParams();

        return $this->render('/product/list.html.twig', [
            'products' => $productList->getProducts(),
            'params' => ['cityEn' => $cityEn, 'page' => $page],
            'location' => $this->location,
            'year' => $productListViewParams->year,
            'yearDates' => $productListViewParams->yearDates,
            'discountDates' => $productListViewParams->discountDates,
            'discountYears' => $productListViewParams->discountYears,
            'activeProductDiscounts' => $productListViewParams->activeProductDiscounts,
            'currentPage' => $page,
            'firstPage' => $productPaginationViewParams->firstPage,
            'lastPage' => $productPaginationViewParams->lastPage,
            'totalPages' => $productPaginationViewParams->totalPages,
        ]);
    }

    /**
     * @Route ("/{cityEn}/product/{id}", name="app_product", methods={"GET"})
     * @param Request $request
     * @return Response
     * @throws Exception
     */
    public function product(Request $request): Response
    {
        $productId = $request->get('id');

        $productItem = new ProductItem($this->location->cityId, $productId);
        $productItem->init($this->productRepository, $this->discountHistoryRepository);
        $productItemViewParams = $productItem->getProductItemViewParams($this->discountRepository);

        return $this->render('/product/product.html.twig', [
            'product' => $productItem->getProduct(),
            'activeDiscounts' => $productItemViewParams->activeDiscounts,
            'discountYears' => $productItemViewParams->discountYears,
            'datesByYears' => $productItemViewParams->datesByYears,
            'discountDatesByYears' => $productItemViewParams->discountDatesByYears,
        ]);
    }

    /**
     * @Route ("/time-limited-discount-data", name="app_time_limited_discount_data", priority="1")
     * @param Request $request
     * @return JsonResponse
     * @throws NonUniqueResultException
     */
    public function timeLimitedDiscountData(Request $request): JsonResponse
    {
        $productId = $request->get('productId');
        $discountDate = $request->get('discountDate');

        $discountHistory = $this->discountHistoryRepository
            ->findByLimit($this->location->cityId, $productId, $discountDate);

        $view = $this->renderView('/product/_partials/productCard.html.twig', [
            'priceDiscount' => $discountHistory->getPriceDiscount(),
            'priceNormal' => $discountHistory->getPriceNormal(),
            'dateBegin' => date('d.m.Y', $discountHistory->getDateBegin()),
            'dateEnd' => date('d.m.Y', $discountHistory->getDateEnd()),
        ]);

        return $this->json(['html' => $view]);
    }

    /**
     * @Route ("/discount-data-by-year", name="app_discount_data_by_year", priority="1")
     * @param Request $request
     * @return JsonResponse
     * @throws Exception
     * @noinspection PhpUnused
     */
    public function discountDataByYear(Request $request): JsonResponse
    {
        $productId = $request->get('productId');
        $year = $request->get('year');

        $productItem = new ProductItem($this->location->cityId, $productId);
        $productItem->init($this->productRepository, $this->discountHistoryRepository);
        $productItemByYearParams = $productItem->getProductItemByYearParams($year);

        $view = $this->renderView('/product/_partials/history.html.twig', [
            'year' => $year,
            'product' => $productItem->getProduct(),
            'yearDates' => $productItemByYearParams->yearDates,
            'discountDates' => $productItemByYearParams->discountDates,
            'discountYears' => $productItemByYearParams->discountYears,
        ]);

        return $this->json(['html' => $view]);
    }

    /**
     * @return Location
     * @throws Exception
     */
    private function getLocation(): Location
    {
        $cities = Cities::list();
        $locationId = (int) ($_COOKIE['discountLocationId'] ?? Cities::MOSCOW_ID);

        $cityItem = $cities[$locationId] ?? null;

        if ($cityItem) {
            $location = new Location();
            $location->cityId = $locationId;
            $location->cityNameRu = $cityItem['ru'];
            $location->cityNameEn = $cityItem['en'];

            return $location;
        }

        throw new Exception('City item not found');
    }
}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-2">
        <div class="col-6">
            <div class="search-form">
                <form action="{{ path('app_index') }}" method="get" class="row">
                    <div class="col-8">
                        <div class="input-group">
                            <label for="search-query" class="visually-hidden"></label>
                            <input type="text"
                                   name="q"
                                   class="form-control"
                                   id="search-query"
                                   placeholder="Найти продукт"
                                   value="{{ app.request.query.get('q') }}"
                            >
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-6 text-end">
            <a href="#"
               class="select-city"
               title="Выбрать город"
               data-bs-toggle="modal"
               data-bs-target="#selectCityModal"
            >
                <!-- Ajax loading -->
            </a>
        </div>
    </div>
    {% if products %}
        {% include '/product/partials/pagination.html.twig' with {
            'currentPage': currentPage,
            'firstPage': firstPage,
            'lastPage': lastPage,
            'totalPages': totalPages,
        } %}

        <div class="products mt-2">
            {% for product in products %}
                {% set productDiscountYears = discountYears[product.productId]|default([]) %}
                <div class="product-block mb-5">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="product-card pt-3">
                                <div class="row">
                                    <div class="col">
                                        <img src="{{ product.imgLink }}" class="img-fluid" alt="{{ product.name }}">
                                    </div>
                                    <div class="col">
                                        <div class="product-item-wrapper">
                                            {% if product.productId in activeProductDiscounts|keys %}
                                                {% set discount = activeProductDiscounts[product.productId] %}
                                                {% include '/product/partials/productCard.html.twig' with {
                                                    'priceDiscount': discount.priceDiscount,
                                                    'priceNormal': discount.priceNormal,
                                                    'dateBegin': discount.dateBegin,
                                                    'dateEnd': discount.dateEnd
                                                } %}
                                            {% else %}
                                                <div class="pt-3 text-center">
                                                    К сожалению, на данный момент по этому продукту нет выгодных предложений
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <small>
                                            {% if productDiscountYears|length > 1 %}
                                                <a href="{{ path('app_product', {'id': product.productId}) }}">{{ product.name }}</a>
                                            {% else %}
                                                {{ product.name }}
                                            {% endif %}
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-9">
                            <div class="discount-history-wrapper">
                                {% set productDiscountDates = discountDates[product.productId]|default([]) %}
                                {% include '/product/partials/history.html.twig' with {
                                    'year': year,
                                    'yearDates': yearDates,
                                    'product': product,
                                    'productDiscountDates': productDiscountDates,
                                    'productDiscountYears': productDiscountYears,
                                } %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% include '/product/partials/pagination.html.twig' with {
            'currentPage': currentPage,
            'firstPage': firstPage,
            'lastPage': lastPage,
            'totalPages': totalPages,
        } %}
    {% else %}
        <div class="text-center fs-3">
            К сожалению, информации по скидкам в выбранном городе у нас пока нет ;-( <br>
            Но они обязательно появятся.
        </div>
    {% endif %}
{% endblock %}

templates/product/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-2">
        <div class="col-6">
            <div class="search-form">
                <form action="{{ path('app_list', params) }}" method="get" class="row">
                    <div class="col-8">
                        <div class="input-group">
                            <label for="search-query" class="visually-hidden"></label>
                            <input type="text"
                                   name="q"
                                   class="form-control"
                                   id="search-query"
                                   placeholder="Найти продукт"
                                   value="{{ app.request.query.get('q') }}"
                            >
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-6 text-end">
            <a href="#"
               class="select-city"
               title="Выбрать город"
               data-bs-toggle="modal"
               data-bs-target="#selectCityModal"
            >
                {{ location.cityNameRu }}
            </a>
        </div>
    </div>
    {% if products %}
        {% include '/product/_partials/pagination.html.twig' with {
            'params': params,
            'currentPage': currentPage,
            'firstPage': firstPage,
            'lastPage': lastPage,
            'totalPages': totalPages,
        } %}

        <div class="products mt-2">
            {% for product in products %}
                {% set productDiscountYears = discountYears[product.productId]|default([]) %}
                <div class="product-block mb-5">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="product-card pt-3">
                                <div class="row">
                                    <div class="col">
                                        <img src="{{ product.imgLink }}" class="img-fluid" alt="{{ product.name }}">
                                    </div>
                                    <div class="col">
                                        <div class="product-item-wrapper">
                                            {% if product.productId in activeProductDiscounts|keys %}
                                                {% set discount = activeProductDiscounts[product.productId] %}
                                                {% include '/product/_partials/productCard.html.twig' with {
                                                    'priceDiscount': discount.priceDiscount,
                                                    'priceNormal': discount.priceNormal,
                                                    'dateBegin': discount.dateBegin,
                                                    'dateEnd': discount.dateEnd
                                                } %}
                                            {% else %}
                                                <div class="pt-3 text-center">
                                                    К сожалению, на данный момент по этому продукту нет выгодных предложений
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <small>
                                            <a href="{{ path('app_product', {'cityEn': params.cityEn, 'id': product.productId}) }}">{{ product.name }}</a>
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-9">
                            <div class="discount-history-wrapper">
                                {% set productDiscountDates = discountDates[product.productId]|default([]) %}
                                {% include '/product/_partials/history.html.twig' with {
                                    'year': year,
                                    'yearDates': yearDates,
                                    'product': product,
                                    'discountDates': productDiscountDates,
                                    'discountYears': productDiscountYears,
                                } %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% include '/product/_partials/pagination.html.twig' with {
            'params': params,
            'currentPage': currentPage,
            'firstPage': firstPage,
            'lastPage': lastPage,
            'totalPages': totalPages,
        } %}
    {% else %}
        <div class="text-center fs-3">
            К сожалению, информации по скидкам в выбранном городе у нас пока нет ;-( <br>
            Но они обязательно появятся.
        </div>
    {% endif %}
{% endblock %}

templates/product/product.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="product-block mt-5">
        <div class="row">
            <div class="col-lg-3">
                <div class="product-card position-fixed" style="width: 306px;">
                    <div class="row">
                        <div class="col">
                            <img src="{{ product.imgPathLink }}" class="img-fluid" alt="{{ product.name }}">
                        </div>
                        <div class="col">
                            <div class="product-item-wrapper">
                                {% if product.productId in activeDiscounts|keys %}
                                    {% set discount = activeDiscounts[product.productId] %}
                                    {% include '/product/_partials/productCard.html.twig' with {
                                        'priceDiscount': discount.priceDiscount,
                                        'priceNormal': discount.priceNormal,
                                        'dateBegin': discount.dateBegin,
                                        'dateEnd': discount.dateEnd
                                    } %}
                                {% else %}
                                    <div class="pt-3 text-center">
                                        К сожалению, на данный момент по этому продукту нет выгодных предложений
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <small>{{ product.name }}</small>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <a href="{{ path('app_index') }}">Назад к списку продуктов</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                {% for year in discountYears %}
                    <div class="discount-history-wrapper">
                        {% include '/product/_partials/history.html.twig' with {
                            'year': year,
                            'yearDates': datesByYears[year],
                            'product': product,
                            'discountDates': discountDatesByYears[year],
                            'discountYears': [year],
                        } %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}